let aircraftKeywords = [
    'OSPREY',
    'B-17 FLYING FORTESS',
    'B-52 STRATOFORTRESS',
    'F-1 MIRRAGE',
    'SUPER ETENDARD',
    'JAGUAR',
    'MIRRAGE 2000C',
    'MIRRAGE III',
    'RAFALE',
    'C-47 SKYTRAIN',

    'F-14 Tomcat',
    'EF-111A Raven',
    'F-16 Fighting Falcon',
    'A-6 Intruder',
    'F-111B',
    'E-2C Hawkeye',
    'C-130 Hercules',
    'F-104 Starfighter',
    'F-114A Nighthawk',
    'SR-71A',
    'MiG-31 Foxhound',
    'F-4 Phantom 2',
    'F-18 Hornet',
    'F-15 Eagle',
    'MiG-21 Fishbed',
    'MiG-23',
    'MiG-25',
    'MiG-27',
    'Su-24 Fencer',
    'Su-27 Flanker',
    'Su-7B Fitter A',
    'Su-25',
    'Su-30',
    'Su-34',
    'Su-9',
    'Tu-16 Badger',
    'Tu-22 Blinder',
    'Tu-26 Backfire',
    'Tu-95MS',
    'Tu-95 Bear',
    'Tu-160',
    ];